language:       scala
scala:
              - 2.11.12
              - 2.12.9
              - 2.13.0
jdk:
              - openjdk8
cache:
              - "~/.ivy2"
              - "~/.sbt"
install:
              - sudo apt-get update
              - sudo apt-get install zsh
              - sudo chmod +x scripts/*
              - ./sbt ++$TRAVIS_SCALA_VERSION update
script:         ./sbt ++$TRAVIS_SCALA_VERSION test
after_script:
              - scripts/prepare-test-results-for-ci.sh
              - find $HOME/.sbt -name "*.lock" | xargs rm
              - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
notifications:
  email:
    on_success: never
    on_failure: change
